# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_shipment_package_dimensions_request import MerchantShipmentPackageDimensionsRequest

class TestMerchantShipmentPackageDimensionsRequest(unittest.TestCase):
    """MerchantShipmentPackageDimensionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantShipmentPackageDimensionsRequest:
        """Test MerchantShipmentPackageDimensionsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantShipmentPackageDimensionsRequest`
        """
        model = MerchantShipmentPackageDimensionsRequest()
        if include_optional:
            return MerchantShipmentPackageDimensionsRequest(
                height = 1.337,
                width = 1.337,
                length = 1.337,
                unit = 'CM'
            )
        else:
            return MerchantShipmentPackageDimensionsRequest(
        )
        """

    def testMerchantShipmentPackageDimensionsRequest(self):
        """Test MerchantShipmentPackageDimensionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
