# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.i_vendor_party import IVendorParty

class TestIVendorParty(unittest.TestCase):
    """IVendorParty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IVendorParty:
        """Test IVendorParty
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IVendorParty`
        """
        model = IVendorParty()
        if include_optional:
            return IVendorParty(
                party_id = '',
                tax_registration_type = 'VAT',
                tax_registration_no = '',
                name = '',
                address_line1 = '',
                address_line2 = '',
                address_line3 = '',
                city = '',
                county = '',
                district = '',
                state_or_region = '',
                postal_code = '',
                country_code = '',
                phone = ''
            )
        else:
            return IVendorParty(
        )
        """

    def testIVendorParty(self):
        """Test IVendorParty"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
