# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_stock_location_with_country_iso_response import MerchantStockLocationWithCountryIsoResponse

class TestMerchantStockLocationWithCountryIsoResponse(unittest.TestCase):
    """MerchantStockLocationWithCountryIsoResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantStockLocationWithCountryIsoResponse:
        """Test MerchantStockLocationWithCountryIsoResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantStockLocationWithCountryIsoResponse`
        """
        model = MerchantStockLocationWithCountryIsoResponse()
        if include_optional:
            return MerchantStockLocationWithCountryIsoResponse(
                id = 56,
                name = '',
                country_iso = ''
            )
        else:
            return MerchantStockLocationWithCountryIsoResponse(
        )
        """

    def testMerchantStockLocationWithCountryIsoResponse(self):
        """Test MerchantStockLocationWithCountryIsoResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
