# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_return_line_request import MerchantReturnLineRequest

class TestMerchantReturnLineRequest(unittest.TestCase):
    """MerchantReturnLineRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantReturnLineRequest:
        """Test MerchantReturnLineRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantReturnLineRequest`
        """
        model = MerchantReturnLineRequest()
        if include_optional:
            return MerchantReturnLineRequest(
                merchant_product_no = '',
                quantity = 0,
                extra_data = {
                    'key' : ''
                    }
            )
        else:
            return MerchantReturnLineRequest(
                merchant_product_no = '',
                quantity = 0,
        )
        """

    def testMerchantReturnLineRequest(self):
        """Test MerchantReturnLineRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
