# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.collection_of_merchant_settlement_reports_response import CollectionOfMerchantSettlementReportsResponse

class TestCollectionOfMerchantSettlementReportsResponse(unittest.TestCase):
    """CollectionOfMerchantSettlementReportsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionOfMerchantSettlementReportsResponse:
        """Test CollectionOfMerchantSettlementReportsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionOfMerchantSettlementReportsResponse`
        """
        model = CollectionOfMerchantSettlementReportsResponse()
        if include_optional:
            return CollectionOfMerchantSettlementReportsResponse(
                content = [
                    openapi_client.models.merchant_settlement_reports_response.MerchantSettlementReportsResponse(
                        settlement_id = 56, 
                        channel_settlement_no = '', 
                        channel_id = 56, 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        transactions_count = 56, )
                    ],
                count = 56,
                total_count = 56,
                items_per_page = 56,
                status_code = 56,
                request_id = '',
                log_id = '',
                success = True,
                message = '',
                exception_type = '',
                validation_errors = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return CollectionOfMerchantSettlementReportsResponse(
        )
        """

    def testCollectionOfMerchantSettlementReportsResponse(self):
        """Test CollectionOfMerchantSettlementReportsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
