# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.purchase_order_line_identifier_type import PurchaseOrderLineIdentifierType

class TestPurchaseOrderLineIdentifierType(unittest.TestCase):
    """PurchaseOrderLineIdentifierType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPurchaseOrderLineIdentifierType(self):
        """Test PurchaseOrderLineIdentifierType"""
        # inst = PurchaseOrderLineIdentifierType()

if __name__ == '__main__':
    unittest.main()
