# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_shipment_label_carrier_request import MerchantShipmentLabelCarrierRequest

class TestMerchantShipmentLabelCarrierRequest(unittest.TestCase):
    """MerchantShipmentLabelCarrierRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantShipmentLabelCarrierRequest:
        """Test MerchantShipmentLabelCarrierRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantShipmentLabelCarrierRequest`
        """
        model = MerchantShipmentLabelCarrierRequest()
        if include_optional:
            return MerchantShipmentLabelCarrierRequest(
                lines = [
                    openapi_client.models.merchant_shipment_line_request.MerchantShipmentLineRequest(
                        merchant_product_no = '', 
                        extra_data = {
                            'key' : ''
                            }, 
                        quantity = 0, )
                    ],
                dimensions = openapi_client.models.merchant_shipment_package_dimensions_request.MerchantShipmentPackageDimensionsRequest(
                    height = 1.337, 
                    width = 1.337, 
                    length = 1.337, 
                    unit = 'CM', ),
                weight = openapi_client.models.merchant_shipment_package_weight_request.MerchantShipmentPackageWeightRequest(
                    value = 1.337, 
                    unit = 'GRAM', )
            )
        else:
            return MerchantShipmentLabelCarrierRequest(
                lines = [
                    openapi_client.models.merchant_shipment_line_request.MerchantShipmentLineRequest(
                        merchant_product_no = '', 
                        extra_data = {
                            'key' : ''
                            }, 
                        quantity = 0, )
                    ],
                dimensions = openapi_client.models.merchant_shipment_package_dimensions_request.MerchantShipmentPackageDimensionsRequest(
                    height = 1.337, 
                    width = 1.337, 
                    length = 1.337, 
                    unit = 'CM', ),
                weight = openapi_client.models.merchant_shipment_package_weight_request.MerchantShipmentPackageWeightRequest(
                    value = 1.337, 
                    unit = 'GRAM', ),
        )
        """

    def testMerchantShipmentLabelCarrierRequest(self):
        """Test MerchantShipmentLabelCarrierRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
