# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.stock_location_api import StockLocationApi


class TestStockLocationApi(unittest.TestCase):
    """StockLocationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StockLocationApi()

    def tearDown(self) -> None:
        pass

    def test_stock_location_create(self) -> None:
        """Test case for stock_location_create

        Creates a stock location
        """
        pass

    def test_stock_location_index(self) -> None:
        """Test case for stock_location_index

        Gets stock locations
        """
        pass


if __name__ == '__main__':
    unittest.main()
