# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_offer_get_stock_response import MerchantOfferGetStockResponse

class TestMerchantOfferGetStockResponse(unittest.TestCase):
    """MerchantOfferGetStockResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantOfferGetStockResponse:
        """Test MerchantOfferGetStockResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantOfferGetStockResponse`
        """
        model = MerchantOfferGetStockResponse()
        if include_optional:
            return MerchantOfferGetStockResponse(
                merchant_product_no = '',
                stock_location_id = 56,
                stock = 56,
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return MerchantOfferGetStockResponse(
        )
        """

    def testMerchantOfferGetStockResponse(self):
        """Test MerchantOfferGetStockResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
