# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.product_extra_data_request import ProductExtraDataRequest

class TestProductExtraDataRequest(unittest.TestCase):
    """ProductExtraDataRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductExtraDataRequest:
        """Test ProductExtraDataRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductExtraDataRequest`
        """
        model = ProductExtraDataRequest()
        if include_optional:
            return ProductExtraDataRequest(
                op = '0',
                key = '',
                value = ''
            )
        else:
            return ProductExtraDataRequest(
                op = '0',
                key = '',
        )
        """

    def testProductExtraDataRequest(self):
        """Test ProductExtraDataRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
