# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_shipment_request import MerchantShipmentRequest

class TestMerchantShipmentRequest(unittest.TestCase):
    """MerchantShipmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantShipmentRequest:
        """Test MerchantShipmentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantShipmentRequest`
        """
        model = MerchantShipmentRequest()
        if include_optional:
            return MerchantShipmentRequest(
                merchant_shipment_no = '',
                merchant_order_no = '',
                lines = [
                    openapi_client.models.merchant_shipment_line_request.MerchantShipmentLineRequest(
                        merchant_product_no = '', 
                        extra_data = {
                            'key' : ''
                            }, 
                        quantity = 0, )
                    ],
                extra_data = {
                    'key' : ''
                    },
                track_trace_no = '',
                track_trace_url = '',
                return_track_trace_no = '',
                method = '',
                shipped_from_country_code = '',
                shipped_from_stock_location_id = 56,
                shipment_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return MerchantShipmentRequest(
                merchant_shipment_no = '',
                merchant_order_no = '',
                lines = [
                    openapi_client.models.merchant_shipment_line_request.MerchantShipmentLineRequest(
                        merchant_product_no = '', 
                        extra_data = {
                            'key' : ''
                            }, 
                        quantity = 0, )
                    ],
        )
        """

    def testMerchantShipmentRequest(self):
        """Test MerchantShipmentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
