# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.collection_of_merchant_product_attribute_group_with_product_extra_data_response import CollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse

class TestCollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse(unittest.TestCase):
    """CollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse:
        """Test CollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse`
        """
        model = CollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse()
        if include_optional:
            return CollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse(
                content = [
                    openapi_client.models.merchant_product_attribute_group_with_product_extra_data_response.MerchantProductAttributeGroupWithProductExtraDataResponse(
                        product_attribute_group_id = 56, 
                        group_name = '', 
                        linked_product_extra_data = [
                            openapi_client.models.merchant_product_extra_data_response.MerchantProductExtraDataResponse(
                                product_extra_data_id = 56, 
                                key = '', )
                            ], )
                    ],
                count = 56,
                total_count = 56,
                items_per_page = 56,
                status_code = 56,
                request_id = '',
                log_id = '',
                success = True,
                message = '',
                exception_type = '',
                validation_errors = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return CollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse(
        )
        """

    def testCollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse(self):
        """Test CollectionOfMerchantProductAttributeGroupWithProductExtraDataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
