# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.freezing_action_request import FreezingActionRequest

class TestFreezingActionRequest(unittest.TestCase):
    """FreezingActionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFreezingActionRequest(self):
        """Test FreezingActionRequest"""
        # inst = FreezingActionRequest()

if __name__ == '__main__':
    unittest.main()
