# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.channel_carrier_recommendation_api import ChannelCarrierRecommendationApi

class TestChannelCarrierRecommendationApi(unittest.TestCase):
    """ChannelCarrierRecommendationApi unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChannelCarrierRecommendationApi(self):
        """Test ChannelCarrierRecommendationApi"""
        # inst = ChannelCarrierRecommendationApi()

if __name__ == '__main__':
    unittest.main()
