# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.competition_price_api import CompetitionPriceApi


class TestCompetitionPriceApi(unittest.TestCase):
    """CompetitionPriceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CompetitionPriceApi()

    def tearDown(self) -> None:
        pass

    def test_competition_prices_get_buy_box_prices(self) -> None:
        """Test case for competition_prices_get_buy_box_prices

        Gets the price from the buy box winner
        """
        pass


if __name__ == '__main__':
    unittest.main()
