# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_return_line_update_request import MerchantReturnLineUpdateRequest

class TestMerchantReturnLineUpdateRequest(unittest.TestCase):
    """MerchantReturnLineUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantReturnLineUpdateRequest:
        """Test MerchantReturnLineUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantReturnLineUpdateRequest`
        """
        model = MerchantReturnLineUpdateRequest()
        if include_optional:
            return MerchantReturnLineUpdateRequest(
                merchant_product_no = '',
                accepted_quantity = 0,
                rejected_quantity = 0
            )
        else:
            return MerchantReturnLineUpdateRequest(
                merchant_product_no = '',
                accepted_quantity = 0,
                rejected_quantity = 0,
        )
        """

    def testMerchantReturnLineUpdateRequest(self):
        """Test MerchantReturnLineUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
