# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_webhook_response import MerchantWebhookResponse

class TestMerchantWebhookResponse(unittest.TestCase):
    """MerchantWebhookResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantWebhookResponse:
        """Test MerchantWebhookResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantWebhookResponse`
        """
        model = MerchantWebhookResponse()
        if include_optional:
            return MerchantWebhookResponse(
                name = '',
                url = '',
                is_active = True,
                events = [
                    'ORDERS_CREATE'
                    ]
            )
        else:
            return MerchantWebhookResponse(
        )
        """

    def testMerchantWebhookResponse(self):
        """Test MerchantWebhookResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
