# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_stock_location_create_request import MerchantStockLocationCreateRequest

class TestMerchantStockLocationCreateRequest(unittest.TestCase):
    """MerchantStockLocationCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantStockLocationCreateRequest:
        """Test MerchantStockLocationCreateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantStockLocationCreateRequest`
        """
        model = MerchantStockLocationCreateRequest()
        if include_optional:
            return MerchantStockLocationCreateRequest(
                name = '0',
                is_default = True,
                fall_back_to_default = True,
                address = openapi_client.models.merchant_stock_location_address_request.MerchantStockLocationAddressRequest(
                    country_iso = '0', 
                    street_name = '', 
                    zip_code = '', 
                    house_nr = '', 
                    house_nr_addition = '', 
                    city = '', 
                    region = '', ),
                phone_number = ''
            )
        else:
            return MerchantStockLocationCreateRequest(
                name = '0',
        )
        """

    def testMerchantStockLocationCreateRequest(self):
        """Test MerchantStockLocationCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
