# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.webhook_api import WebhookApi


class TestWebhookApi(unittest.TestCase):
    """WebhookApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhookApi()

    def tearDown(self) -> None:
        pass

    def test_webhooks_create(self) -> None:
        """Test case for webhooks_create

        Creates a webhook
        """
        pass

    def test_webhooks_delete(self) -> None:
        """Test case for webhooks_delete

        Deletes a webhook
        """
        pass

    def test_webhooks_get_all(self) -> None:
        """Test case for webhooks_get_all

        Gets webhooks
        """
        pass

    def test_webhooks_update(self) -> None:
        """Test case for webhooks_update

        Updates a webhook
        """
        pass


if __name__ == '__main__':
    unittest.main()
