# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.report_status import ReportStatus

class TestReportStatus(unittest.TestCase):
    """ReportStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReportStatus(self):
        """Test ReportStatus"""
        # inst = ReportStatus()

if __name__ == '__main__':
    unittest.main()
