# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_offer_stock_update_request import MerchantOfferStockUpdateRequest

class TestMerchantOfferStockUpdateRequest(unittest.TestCase):
    """MerchantOfferStockUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantOfferStockUpdateRequest:
        """Test MerchantOfferStockUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantOfferStockUpdateRequest`
        """
        model = MerchantOfferStockUpdateRequest()
        if include_optional:
            return MerchantOfferStockUpdateRequest(
                merchant_product_no = '',
                stock_locations = [
                    openapi_client.models.merchant_stock_location_update_request.MerchantStockLocationUpdateRequest(
                        stock = 0, 
                        stock_location_id = 56, )
                    ]
            )
        else:
            return MerchantOfferStockUpdateRequest(
                merchant_product_no = '',
                stock_locations = [
                    openapi_client.models.merchant_stock_location_update_request.MerchantStockLocationUpdateRequest(
                        stock = 0, 
                        stock_location_id = 56, )
                    ],
        )
        """

    def testMerchantOfferStockUpdateRequest(self):
        """Test MerchantOfferStockUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
