# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.collection_of_channel_global_channel_response import CollectionOfChannelGlobalChannelResponse

class TestCollectionOfChannelGlobalChannelResponse(unittest.TestCase):
    """CollectionOfChannelGlobalChannelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionOfChannelGlobalChannelResponse:
        """Test CollectionOfChannelGlobalChannelResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionOfChannelGlobalChannelResponse`
        """
        model = CollectionOfChannelGlobalChannelResponse()
        if include_optional:
            return CollectionOfChannelGlobalChannelResponse(
                content = [
                    openapi_client.models.channel_global_channel_response.ChannelGlobalChannelResponse(
                        country_code = '', 
                        global_channel_id = 56, 
                        channels = [
                            openapi_client.models.channel_channel_response.ChannelChannelResponse(
                                channel_id = 56, 
                                is_enabled = True, 
                                channel_name = '', 
                                reference = '', )
                            ], 
                        language_code = '', 
                        global_channel_name = '', )
                    ],
                count = 56,
                total_count = 56,
                items_per_page = 56,
                status_code = 56,
                request_id = '',
                log_id = '',
                success = True,
                message = '',
                exception_type = '',
                validation_errors = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return CollectionOfChannelGlobalChannelResponse(
        )
        """

    def testCollectionOfChannelGlobalChannelResponse(self):
        """Test CollectionOfChannelGlobalChannelResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
