# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.purchase_orders_api import PurchaseOrdersApi


class TestPurchaseOrdersApi(unittest.TestCase):
    """PurchaseOrdersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PurchaseOrdersApi()

    def tearDown(self) -> None:
        pass

    def test_acknowledge(self) -> None:
        """Test case for acknowledge

        Acknowledges lines of a purchase order
        """
        pass

    def test_create(self) -> None:
        """Test case for create

        Create a purchase order shipment.
        """
        pass

    def test_create_invoice(self) -> None:
        """Test case for create_invoice

        Creates a purchase order invoice
        """
        pass

    def test_create_invoices(self) -> None:
        """Test case for create_invoices

        Creates a purchase order invoices in a bulk
        """
        pass

    def test_get_by_filter(self) -> None:
        """Test case for get_by_filter

        Gets purchase orders by filter
        """
        pass

    def test_get_by_filter_shipment_merchant(self) -> None:
        """Test case for get_by_filter_shipment_merchant

        Gets purchase order shipments by filter
        """
        pass

    def test_update(self) -> None:
        """Test case for update

        Update a purchase order shipment.
        """
        pass


if __name__ == '__main__':
    unittest.main()
