# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.single_of_api_response import SingleOfApiResponse

class TestSingleOfApiResponse(unittest.TestCase):
    """SingleOfApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SingleOfApiResponse:
        """Test SingleOfApiResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleOfApiResponse`
        """
        model = SingleOfApiResponse()
        if include_optional:
            return SingleOfApiResponse(
                content = openapi_client.models.api_response.ApiResponse(
                    status_code = 56, 
                    request_id = '', 
                    log_id = '', 
                    success = True, 
                    message = '', 
                    exception_type = '', 
                    validation_errors = {
                        'key' : [
                            ''
                            ]
                        }, ),
                status_code = 56,
                request_id = '',
                log_id = '',
                success = True,
                message = '',
                exception_type = '',
                validation_errors = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return SingleOfApiResponse(
        )
        """

    def testSingleOfApiResponse(self):
        """Test SingleOfApiResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
