# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.advance_settings_response import AdvanceSettingsResponse

class TestAdvanceSettingsResponse(unittest.TestCase):
    """AdvanceSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AdvanceSettingsResponse:
        """Test AdvanceSettingsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AdvanceSettingsResponse`
        """
        model = AdvanceSettingsResponse()
        if include_optional:
            return AdvanceSettingsResponse(
                manage_stock = True,
                disable_address_validation = True,
                skip_house_number_validation = True,
                skip_house_number_validation_for_country_codes = [
                    ''
                    ],
                set_orders_to_closed_on_import = True,
                disable_stock_reservation = True,
                disable_auto_order_cancellation = True,
                automatically_set_phone_number_if_empty = '',
                default_vat_rate = 1.337,
                order_too_long_on_new_hours_offset = 56
            )
        else:
            return AdvanceSettingsResponse(
        )
        """

    def testAdvanceSettingsResponse(self):
        """Test AdvanceSettingsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
