# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_stock_price_update_request import MerchantStockPriceUpdateRequest

class TestMerchantStockPriceUpdateRequest(unittest.TestCase):
    """MerchantStockPriceUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantStockPriceUpdateRequest:
        """Test MerchantStockPriceUpdateRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantStockPriceUpdateRequest`
        """
        model = MerchantStockPriceUpdateRequest()
        if include_optional:
            return MerchantStockPriceUpdateRequest(
                merchant_product_no = '',
                stock = 0,
                price = 0,
                stock_location_id = 56
            )
        else:
            return MerchantStockPriceUpdateRequest(
                merchant_product_no = '',
        )
        """

    def testMerchantStockPriceUpdateRequest(self):
        """Test MerchantStockPriceUpdateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
