# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.fulfillment_stock_api import FulfillmentStockApi


class TestFulfillmentStockApi(unittest.TestCase):
    """FulfillmentStockApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FulfillmentStockApi()

    def tearDown(self) -> None:
        pass

    def test_fulfillment_stock_get_fulfillement_stock_with_stock_locations(self) -> None:
        """Test case for fulfillment_stock_get_fulfillement_stock_with_stock_locations

        Gets product stock across all warehouses with stock locations
        """
        pass


if __name__ == '__main__':
    unittest.main()
