# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_channel_label_shipment_request import MerchantChannelLabelShipmentRequest

class TestMerchantChannelLabelShipmentRequest(unittest.TestCase):
    """MerchantChannelLabelShipmentRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantChannelLabelShipmentRequest:
        """Test MerchantChannelLabelShipmentRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantChannelLabelShipmentRequest`
        """
        model = MerchantChannelLabelShipmentRequest()
        if include_optional:
            return MerchantChannelLabelShipmentRequest(
                dimensions = openapi_client.models.merchant_shipment_package_dimensions_request.MerchantShipmentPackageDimensionsRequest(
                    height = 1.337, 
                    width = 1.337, 
                    length = 1.337, 
                    unit = 'CM', ),
                weight = openapi_client.models.merchant_shipment_package_weight_request.MerchantShipmentPackageWeightRequest(
                    value = 1.337, 
                    unit = 'GRAM', ),
                channel_method_code = '0',
                merchant_shipment_no = '',
                merchant_order_no = '',
                shipped_from_country_code = '',
                shipped_from_stock_location_id = 56,
                lines = [
                    openapi_client.models.merchant_shipment_line_request.MerchantShipmentLineRequest(
                        merchant_product_no = '', 
                        extra_data = {
                            'key' : ''
                            }, 
                        quantity = 0, )
                    ]
            )
        else:
            return MerchantChannelLabelShipmentRequest(
                dimensions = openapi_client.models.merchant_shipment_package_dimensions_request.MerchantShipmentPackageDimensionsRequest(
                    height = 1.337, 
                    width = 1.337, 
                    length = 1.337, 
                    unit = 'CM', ),
                weight = openapi_client.models.merchant_shipment_package_weight_request.MerchantShipmentPackageWeightRequest(
                    value = 1.337, 
                    unit = 'GRAM', ),
                channel_method_code = '0',
                merchant_shipment_no = '',
                merchant_order_no = '',
                lines = [
                    openapi_client.models.merchant_shipment_line_request.MerchantShipmentLineRequest(
                        merchant_product_no = '', 
                        extra_data = {
                            'key' : ''
                            }, 
                        quantity = 0, )
                    ],
        )
        """

    def testMerchantChannelLabelShipmentRequest(self):
        """Test MerchantChannelLabelShipmentRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
