# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.single_of_dictionary_of_string_and_list_of_string import SingleOfDictionaryOfStringAndListOfString

class TestSingleOfDictionaryOfStringAndListOfString(unittest.TestCase):
    """SingleOfDictionaryOfStringAndListOfString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SingleOfDictionaryOfStringAndListOfString:
        """Test SingleOfDictionaryOfStringAndListOfString
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SingleOfDictionaryOfStringAndListOfString`
        """
        model = SingleOfDictionaryOfStringAndListOfString()
        if include_optional:
            return SingleOfDictionaryOfStringAndListOfString(
                content = {
                    'key' : [
                        ''
                        ]
                    },
                status_code = 56,
                request_id = '',
                log_id = '',
                success = True,
                message = '',
                exception_type = '',
                validation_errors = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return SingleOfDictionaryOfStringAndListOfString(
        )
        """

    def testSingleOfDictionaryOfStringAndListOfString(self):
        """Test SingleOfDictionaryOfStringAndListOfString"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
