# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.product_attribute_group_api import ProductAttributeGroupApi


class TestProductAttributeGroupApi(unittest.TestCase):
    """ProductAttributeGroupApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProductAttributeGroupApi()

    def tearDown(self) -> None:
        pass

    def test_product_attribute_group_add_product_extra_data(self) -> None:
        """Test case for product_attribute_group_add_product_extra_data

        Adds custom attributes to a group
        """
        pass

    def test_product_attribute_group_create(self) -> None:
        """Test case for product_attribute_group_create

        Creates a custom attribute group
        """
        pass

    def test_product_attribute_group_delete(self) -> None:
        """Test case for product_attribute_group_delete

        Deletes a custom attribute group
        """
        pass

    def test_product_attribute_group_get_by_filter(self) -> None:
        """Test case for product_attribute_group_get_by_filter

        Gets custom attribute groups
        """
        pass

    def test_product_attribute_group_get_with_channels_by_filter(self) -> None:
        """Test case for product_attribute_group_get_with_channels_by_filter

        Gets custom attribute groups and linked marketplaces
        """
        pass

    def test_product_attribute_group_remove_product_extra_data(self) -> None:
        """Test case for product_attribute_group_remove_product_extra_data

        Deletes custom attributes from a group
        """
        pass

    def test_product_attribute_group_rename_product_attribute_group(self) -> None:
        """Test case for product_attribute_group_rename_product_attribute_group

        Renames custom attribute groups
        """
        pass


if __name__ == '__main__':
    unittest.main()
