# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.settlement_api import SettlementApi


class TestSettlementApi(unittest.TestCase):
    """SettlementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SettlementApi()

    def tearDown(self) -> None:
        pass

    def test_settlement_get_by_filter(self) -> None:
        """Test case for settlement_get_by_filter

        Gets settlements
        """
        pass

    def test_settlement_upload_settlement(self) -> None:
        """Test case for settlement_upload_settlement

        Imports a settlement file.
        """
        pass


if __name__ == '__main__':
    unittest.main()
