# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.shipment_fulfillment_type import ShipmentFulfillmentType

class TestShipmentFulfillmentType(unittest.TestCase):
    """ShipmentFulfillmentType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testShipmentFulfillmentType(self):
        """Test ShipmentFulfillmentType"""
        # inst = ShipmentFulfillmentType()

if __name__ == '__main__':
    unittest.main()
