# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.collection_of_merchant_product_bundle_response import CollectionOfMerchantProductBundleResponse

class TestCollectionOfMerchantProductBundleResponse(unittest.TestCase):
    """CollectionOfMerchantProductBundleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionOfMerchantProductBundleResponse:
        """Test CollectionOfMerchantProductBundleResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionOfMerchantProductBundleResponse`
        """
        model = CollectionOfMerchantProductBundleResponse()
        if include_optional:
            return CollectionOfMerchantProductBundleResponse(
                content = [
                    openapi_client.models.merchant_product_bundle_response.MerchantProductBundleResponse(
                        merchant_product_no = '', 
                        ean = '', 
                        name = '', 
                        price = 1.337, 
                        parts = [
                            openapi_client.models.merchant_product_bundle_part_response.MerchantProductBundlePartResponse(
                                merchant_product_no = '', 
                                ean = '', 
                                name = '', 
                                quantity = 56, 
                                price = 1.337, )
                            ], )
                    ],
                count = 56,
                total_count = 56,
                items_per_page = 56,
                status_code = 56,
                request_id = '',
                log_id = '',
                success = True,
                message = '',
                exception_type = '',
                validation_errors = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return CollectionOfMerchantProductBundleResponse(
        )
        """

    def testCollectionOfMerchantProductBundleResponse(self):
        """Test CollectionOfMerchantProductBundleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
