# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_product_attribute_group_with_product_extra_data_response import MerchantProductAttributeGroupWithProductExtraDataResponse

class TestMerchantProductAttributeGroupWithProductExtraDataResponse(unittest.TestCase):
    """MerchantProductAttributeGroupWithProductExtraDataResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantProductAttributeGroupWithProductExtraDataResponse:
        """Test MerchantProductAttributeGroupWithProductExtraDataResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantProductAttributeGroupWithProductExtraDataResponse`
        """
        model = MerchantProductAttributeGroupWithProductExtraDataResponse()
        if include_optional:
            return MerchantProductAttributeGroupWithProductExtraDataResponse(
                product_attribute_group_id = 56,
                group_name = '',
                linked_product_extra_data = [
                    openapi_client.models.merchant_product_extra_data_response.MerchantProductExtraDataResponse(
                        product_extra_data_id = 56, 
                        key = '', )
                    ]
            )
        else:
            return MerchantProductAttributeGroupWithProductExtraDataResponse(
        )
        """

    def testMerchantProductAttributeGroupWithProductExtraDataResponse(self):
        """Test MerchantProductAttributeGroupWithProductExtraDataResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
