# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.cancellation_api import CancellationApi


class TestCancellationApi(unittest.TestCase):
    """CancellationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CancellationApi()

    def tearDown(self) -> None:
        pass

    def test_cancellation_create(self) -> None:
        """Test case for cancellation_create

        Creates a cancelation
        """
        pass

    def test_cancellation_get_for_merchant(self) -> None:
        """Test case for cancellation_get_for_merchant

        Gets cancelations
        """
        pass


if __name__ == '__main__':
    unittest.main()
