# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.merchant_stock_location_address_request import MerchantStockLocationAddressRequest

class TestMerchantStockLocationAddressRequest(unittest.TestCase):
    """MerchantStockLocationAddressRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantStockLocationAddressRequest:
        """Test MerchantStockLocationAddressRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantStockLocationAddressRequest`
        """
        model = MerchantStockLocationAddressRequest()
        if include_optional:
            return MerchantStockLocationAddressRequest(
                country_iso = '0',
                street_name = '',
                zip_code = '',
                house_nr = '',
                house_nr_addition = '',
                city = '',
                region = ''
            )
        else:
            return MerchantStockLocationAddressRequest(
                country_iso = '0',
        )
        """

    def testMerchantStockLocationAddressRequest(self):
        """Test MerchantStockLocationAddressRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
