# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Condition(str, Enum):
    """
    Condition
    """

    """
    allowed enum values
    """
    NEW = 'NEW'
    NEW_REFURBISHED = 'NEW_REFURBISHED'
    USED_AS_NEW = 'USED_AS_NEW'
    USED_GOOD = 'USED_GOOD'
    USED_REASONABLE = 'USED_REASONABLE'
    USED_MEDIOCRE = 'USED_MEDIOCRE'
    UNKNOWN = 'UNKNOWN'
    USED_VERY_GOOD = 'USED_VERY_GOOD'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Condition from a JSON string"""
        return cls(json.loads(json_str))


