# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.purchase_order_line_unit_of_measure import PurchaseOrderLineUnitOfMeasure
from typing import Optional, Set
from typing_extensions import Self

class IPurchaseOrderShipmentLineByFilter(BaseModel):
    """
    IPurchaseOrderShipmentLineByFilter
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="ChannelEngine identifier of the shipment line", alias="Id")
    channel_order_no: Optional[StrictStr] = Field(default=None, description="The number the channel uses to identify the purchase order,  which this line (partially) ships.", alias="ChannelOrderNo")
    item_sequence_number: Optional[StrictStr] = Field(default=None, description="Item sequence number for the item. The first item will be 001, the second 002, and so on.  This number is used as a reference to refer to this item from the carton or pallet level.", alias="ItemSequenceNumber")
    channel_product_no: Optional[StrictStr] = Field(default=None, description="The number the channel uses to identify the product", alias="ChannelProductNo")
    merchant_product_no: Optional[StrictStr] = Field(default=None, description="The number the merchant uses to identify the product", alias="MerchantProductNo")
    quantity_unit_of_measure: Optional[PurchaseOrderLineUnitOfMeasure] = Field(default=None, alias="QuantityUnitOfMeasure")
    quantity: Optional[StrictInt] = Field(default=None, description="The quantity", alias="Quantity")
    quantity_unit_size: Optional[StrictInt] = Field(default=None, description="The case size, in the event that we ordered using cases. Otherwise, it is 1.", alias="QuantityUnitSize")
    expiry_date: Optional[datetime] = Field(default=None, description="The date that determines the limit of consumption or use of a product.  For perishable products.", alias="ExpiryDate")
    __properties: ClassVar[List[str]] = ["Id", "ChannelOrderNo", "ItemSequenceNumber", "ChannelProductNo", "MerchantProductNo", "QuantityUnitOfMeasure", "Quantity", "QuantityUnitSize", "ExpiryDate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IPurchaseOrderShipmentLineByFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['Id'] = None

        # set to None if channel_order_no (nullable) is None
        # and model_fields_set contains the field
        if self.channel_order_no is None and "channel_order_no" in self.model_fields_set:
            _dict['ChannelOrderNo'] = None

        # set to None if item_sequence_number (nullable) is None
        # and model_fields_set contains the field
        if self.item_sequence_number is None and "item_sequence_number" in self.model_fields_set:
            _dict['ItemSequenceNumber'] = None

        # set to None if channel_product_no (nullable) is None
        # and model_fields_set contains the field
        if self.channel_product_no is None and "channel_product_no" in self.model_fields_set:
            _dict['ChannelProductNo'] = None

        # set to None if merchant_product_no (nullable) is None
        # and model_fields_set contains the field
        if self.merchant_product_no is None and "merchant_product_no" in self.model_fields_set:
            _dict['MerchantProductNo'] = None

        # set to None if quantity_unit_size (nullable) is None
        # and model_fields_set contains the field
        if self.quantity_unit_size is None and "quantity_unit_size" in self.model_fields_set:
            _dict['QuantityUnitSize'] = None

        # set to None if expiry_date (nullable) is None
        # and model_fields_set contains the field
        if self.expiry_date is None and "expiry_date" in self.model_fields_set:
            _dict['ExpiryDate'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IPurchaseOrderShipmentLineByFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id"),
            "ChannelOrderNo": obj.get("ChannelOrderNo"),
            "ItemSequenceNumber": obj.get("ItemSequenceNumber"),
            "ChannelProductNo": obj.get("ChannelProductNo"),
            "MerchantProductNo": obj.get("MerchantProductNo"),
            "QuantityUnitOfMeasure": obj.get("QuantityUnitOfMeasure"),
            "Quantity": obj.get("Quantity"),
            "QuantityUnitSize": obj.get("QuantityUnitSize"),
            "ExpiryDate": obj.get("ExpiryDate")
        })
        return _obj


