# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.extra_data_type import ExtraDataType
from typing import Optional, Set
from typing_extensions import Self

class MerchantProductExtraDataItemRequest(BaseModel):
    """
    MerchantProductExtraDataItemRequest
    """ # noqa: E501
    key: Annotated[str, Field(min_length=0, strict=True, max_length=100)] = Field(description="Name of the extra data field.", alias="Key")
    value: Optional[StrictStr] = Field(default=None, description="Value of the extra data field.", alias="Value")
    type: Optional[ExtraDataType] = Field(default=None, alias="Type")
    is_public: Optional[StrictBool] = Field(default=None, description="Add this field to the export of the product feed to the channel.", alias="IsPublic")
    language_iso_code: Optional[StrictStr] = Field(default=None, description="The 2-letter ISO code of the extra data", alias="LanguageIsoCode")
    __properties: ClassVar[List[str]] = ["Key", "Value", "Type", "IsPublic", "LanguageIsoCode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MerchantProductExtraDataItemRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if value (nullable) is None
        # and model_fields_set contains the field
        if self.value is None and "value" in self.model_fields_set:
            _dict['Value'] = None

        # set to None if language_iso_code (nullable) is None
        # and model_fields_set contains the field
        if self.language_iso_code is None and "language_iso_code" in self.model_fields_set:
            _dict['LanguageIsoCode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MerchantProductExtraDataItemRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Key": obj.get("Key"),
            "Value": obj.get("Value"),
            "Type": obj.get("Type"),
            "IsPublic": obj.get("IsPublic"),
            "LanguageIsoCode": obj.get("LanguageIsoCode")
        })
        return _obj


