# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.gender import Gender
from typing import Optional, Set
from typing_extensions import Self

class MerchantAddressResponse(BaseModel):
    """
    MerchantAddressResponse
    """ # noqa: E501
    line1: Optional[StrictStr] = Field(default=None, description="The first address line, use this field if address validation is disabled in ChannelEngine.", alias="Line1")
    line2: Optional[StrictStr] = Field(default=None, description="The second address line, use this field if address validation is disabled in ChannelEngine.", alias="Line2")
    line3: Optional[StrictStr] = Field(default=None, description="The third address line, use this field if address validation is disabled in ChannelEngine.", alias="Line3")
    gender: Optional[Gender] = Field(default=None, alias="Gender")
    company_name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, description="Optional. Company addressed too.", alias="CompanyName")
    first_name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, description="The first name of the customer.", alias="FirstName")
    last_name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, description="The last name of the customer (includes the surname prefix [tussenvoegsel] like 'de', 'van', 'du').", alias="LastName")
    street_name: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, description="The name of the street (without house number information)  This field might be empty if address validation is disabled in ChannelEngine.", alias="StreetName")
    house_nr: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, description="The house number  This field might be empty if address validation is disabled in ChannelEngine.", alias="HouseNr")
    house_nr_addition: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, description="Optional. Addition to the house number  If the address is: Groenhazengracht 2c, the address will be:  StreetName: Groenhazengracht  HouseNo: 2  HouseNrAddition: c  This field might be empty if address validation is disabled in ChannelEngine.", alias="HouseNrAddition")
    zip_code: Optional[StrictStr] = Field(default=None, description="The zip or postal code.", alias="ZipCode")
    city: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, description="The name of the city.", alias="City")
    region: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=50)]] = Field(default=None, description="Optional. State/province/region.", alias="Region")
    country_iso: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=2)]] = Field(default=None, description="For example: NL, BE, FR.", alias="CountryIso")
    original: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=256)]] = Field(default=None, description="Optional. The address as a single string: use in case the address lines are entered  as single lines and later parsed into street, house number and house number addition.", alias="Original")
    __properties: ClassVar[List[str]] = ["Line1", "Line2", "Line3", "Gender", "CompanyName", "FirstName", "LastName", "StreetName", "HouseNr", "HouseNrAddition", "ZipCode", "City", "Region", "CountryIso", "Original"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MerchantAddressResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if line1 (nullable) is None
        # and model_fields_set contains the field
        if self.line1 is None and "line1" in self.model_fields_set:
            _dict['Line1'] = None

        # set to None if line2 (nullable) is None
        # and model_fields_set contains the field
        if self.line2 is None and "line2" in self.model_fields_set:
            _dict['Line2'] = None

        # set to None if line3 (nullable) is None
        # and model_fields_set contains the field
        if self.line3 is None and "line3" in self.model_fields_set:
            _dict['Line3'] = None

        # set to None if company_name (nullable) is None
        # and model_fields_set contains the field
        if self.company_name is None and "company_name" in self.model_fields_set:
            _dict['CompanyName'] = None

        # set to None if first_name (nullable) is None
        # and model_fields_set contains the field
        if self.first_name is None and "first_name" in self.model_fields_set:
            _dict['FirstName'] = None

        # set to None if last_name (nullable) is None
        # and model_fields_set contains the field
        if self.last_name is None and "last_name" in self.model_fields_set:
            _dict['LastName'] = None

        # set to None if street_name (nullable) is None
        # and model_fields_set contains the field
        if self.street_name is None and "street_name" in self.model_fields_set:
            _dict['StreetName'] = None

        # set to None if house_nr (nullable) is None
        # and model_fields_set contains the field
        if self.house_nr is None and "house_nr" in self.model_fields_set:
            _dict['HouseNr'] = None

        # set to None if house_nr_addition (nullable) is None
        # and model_fields_set contains the field
        if self.house_nr_addition is None and "house_nr_addition" in self.model_fields_set:
            _dict['HouseNrAddition'] = None

        # set to None if zip_code (nullable) is None
        # and model_fields_set contains the field
        if self.zip_code is None and "zip_code" in self.model_fields_set:
            _dict['ZipCode'] = None

        # set to None if city (nullable) is None
        # and model_fields_set contains the field
        if self.city is None and "city" in self.model_fields_set:
            _dict['City'] = None

        # set to None if region (nullable) is None
        # and model_fields_set contains the field
        if self.region is None and "region" in self.model_fields_set:
            _dict['Region'] = None

        # set to None if country_iso (nullable) is None
        # and model_fields_set contains the field
        if self.country_iso is None and "country_iso" in self.model_fields_set:
            _dict['CountryIso'] = None

        # set to None if original (nullable) is None
        # and model_fields_set contains the field
        if self.original is None and "original" in self.model_fields_set:
            _dict['Original'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MerchantAddressResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Line1": obj.get("Line1"),
            "Line2": obj.get("Line2"),
            "Line3": obj.get("Line3"),
            "Gender": obj.get("Gender"),
            "CompanyName": obj.get("CompanyName"),
            "FirstName": obj.get("FirstName"),
            "LastName": obj.get("LastName"),
            "StreetName": obj.get("StreetName"),
            "HouseNr": obj.get("HouseNr"),
            "HouseNrAddition": obj.get("HouseNrAddition"),
            "ZipCode": obj.get("ZipCode"),
            "City": obj.get("City"),
            "Region": obj.get("Region"),
            "CountryIso": obj.get("CountryIso"),
            "Original": obj.get("Original")
        })
        return _obj


