# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.manco_reason import MancoReason
from openapi_client.models.merchant_cancellation_line_response import MerchantCancellationLineResponse
from typing import Optional, Set
from typing_extensions import Self

class MerchantCancellationResponse(BaseModel):
    """
    MerchantCancellationResponse
    """ # noqa: E501
    id: Optional[StrictInt] = Field(default=None, description="The unique cancellation identifier used by ChannelEngine.", alias="Id")
    merchant_cancellation_no: Annotated[str, Field(min_length=0, strict=True, max_length=250)] = Field(description="The unique cancellation reference used by the Merchant (sku).", alias="MerchantCancellationNo")
    merchant_order_no: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The unique order reference used by the Merchant.", alias="MerchantOrderNo")
    channel_order_no: Optional[StrictStr] = Field(default=None, description="The unique order reference used by the Channel.", alias="ChannelOrderNo")
    lines: List[MerchantCancellationLineResponse] = Field(alias="Lines")
    created_at: Optional[datetime] = Field(default=None, description="The date at which the cancellation was created in ChannelEngine.", alias="CreatedAt")
    reason: Optional[StrictStr] = Field(default=None, description="Reason for cancellation (text).", alias="Reason")
    reason_code: Optional[MancoReason] = Field(default=None, alias="ReasonCode")
    __properties: ClassVar[List[str]] = ["Id", "MerchantCancellationNo", "MerchantOrderNo", "ChannelOrderNo", "Lines", "CreatedAt", "Reason", "ReasonCode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MerchantCancellationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in lines (list)
        _items = []
        if self.lines:
            for _item in self.lines:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Lines'] = _items
        # set to None if channel_order_no (nullable) is None
        # and model_fields_set contains the field
        if self.channel_order_no is None and "channel_order_no" in self.model_fields_set:
            _dict['ChannelOrderNo'] = None

        # set to None if reason (nullable) is None
        # and model_fields_set contains the field
        if self.reason is None and "reason" in self.model_fields_set:
            _dict['Reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MerchantCancellationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Id": obj.get("Id"),
            "MerchantCancellationNo": obj.get("MerchantCancellationNo"),
            "MerchantOrderNo": obj.get("MerchantOrderNo"),
            "ChannelOrderNo": obj.get("ChannelOrderNo"),
            "Lines": [MerchantCancellationLineResponse.from_dict(_item) for _item in obj["Lines"]] if obj.get("Lines") is not None else None,
            "CreatedAt": obj.get("CreatedAt"),
            "Reason": obj.get("Reason"),
            "ReasonCode": obj.get("ReasonCode")
        })
        return _obj


