# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.merchant_shipment_line_request import MerchantShipmentLineRequest
from openapi_client.models.merchant_shipment_package_dimensions_request import MerchantShipmentPackageDimensionsRequest
from openapi_client.models.merchant_shipment_package_weight_request import MerchantShipmentPackageWeightRequest
from typing import Optional, Set
from typing_extensions import Self

class MerchantChannelLabelShipmentRequest(BaseModel):
    """
    MerchantChannelLabelShipmentRequest
    """ # noqa: E501
    dimensions: MerchantShipmentPackageDimensionsRequest = Field(alias="Dimensions")
    weight: MerchantShipmentPackageWeightRequest = Field(alias="Weight")
    channel_method_code: Annotated[str, Field(min_length=1, strict=True)] = Field(alias="ChannelMethodCode")
    merchant_shipment_no: Annotated[str, Field(min_length=0, strict=True, max_length=250)] = Field(description="The unique shipment reference used by the Merchant.", alias="MerchantShipmentNo")
    merchant_order_no: Annotated[str, Field(min_length=0, strict=True, max_length=50)] = Field(description="The unique order reference used by the Merchant.", alias="MerchantOrderNo")
    shipped_from_country_code: Optional[Annotated[str, Field(min_length=0, strict=True, max_length=3)]] = Field(default=None, description="The code of the country from where the package is being shipped.", alias="ShippedFromCountryCode")
    shipped_from_stock_location_id: Optional[StrictInt] = Field(default=None, alias="ShippedFromStockLocationId")
    lines: Annotated[List[MerchantShipmentLineRequest], Field(min_length=1)] = Field(alias="Lines")
    __properties: ClassVar[List[str]] = ["Dimensions", "Weight", "ChannelMethodCode", "MerchantShipmentNo", "MerchantOrderNo", "ShippedFromCountryCode", "ShippedFromStockLocationId", "Lines"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MerchantChannelLabelShipmentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dimensions
        if self.dimensions:
            _dict['Dimensions'] = self.dimensions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of weight
        if self.weight:
            _dict['Weight'] = self.weight.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in lines (list)
        _items = []
        if self.lines:
            for _item in self.lines:
                if _item:
                    _items.append(_item.to_dict())
            _dict['Lines'] = _items
        # set to None if shipped_from_country_code (nullable) is None
        # and model_fields_set contains the field
        if self.shipped_from_country_code is None and "shipped_from_country_code" in self.model_fields_set:
            _dict['ShippedFromCountryCode'] = None

        # set to None if shipped_from_stock_location_id (nullable) is None
        # and model_fields_set contains the field
        if self.shipped_from_stock_location_id is None and "shipped_from_stock_location_id" in self.model_fields_set:
            _dict['ShippedFromStockLocationId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MerchantChannelLabelShipmentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Dimensions": MerchantShipmentPackageDimensionsRequest.from_dict(obj["Dimensions"]) if obj.get("Dimensions") is not None else None,
            "Weight": MerchantShipmentPackageWeightRequest.from_dict(obj["Weight"]) if obj.get("Weight") is not None else None,
            "ChannelMethodCode": obj.get("ChannelMethodCode"),
            "MerchantShipmentNo": obj.get("MerchantShipmentNo"),
            "MerchantOrderNo": obj.get("MerchantOrderNo"),
            "ShippedFromCountryCode": obj.get("ShippedFromCountryCode"),
            "ShippedFromStockLocationId": obj.get("ShippedFromStockLocationId"),
            "Lines": [MerchantShipmentLineRequest.from_dict(_item) for _item in obj["Lines"]] if obj.get("Lines") is not None else None
        })
        return _obj


