# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from openapi_client.models.merchant_order_line_response import MerchantOrderLineResponse
from openapi_client.models.shipment_line_status import ShipmentLineStatus
from typing import Optional, Set
from typing_extensions import Self

class MerchantShipmentLineResponse(BaseModel):
    """
    MerchantShipmentLineResponse
    """ # noqa: E501
    merchant_product_no: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The unique product reference used by the Merchant.", alias="MerchantProductNo")
    merchant_bundle_product_no: Optional[StrictStr] = Field(default=None, description="The unique bundle product reference used by the Merchant.", alias="MerchantBundleProductNo")
    channel_product_no: Optional[StrictStr] = Field(default=None, description="The unique product reference used by the Channel.", alias="ChannelProductNo")
    order_line: Optional[MerchantOrderLineResponse] = Field(default=None, alias="OrderLine")
    shipment_status: Optional[ShipmentLineStatus] = Field(default=None, alias="ShipmentStatus")
    extra_data: Optional[Dict[str, Optional[StrictStr]]] = Field(default=None, description="Extra data on the shipment line. Each item must have an unqiue key", alias="ExtraData")
    quantity: Annotated[int, Field(strict=True, ge=0)] = Field(description="Number of items of the product in the shipment.", alias="Quantity")
    __properties: ClassVar[List[str]] = ["MerchantProductNo", "MerchantBundleProductNo", "ChannelProductNo", "OrderLine", "ShipmentStatus", "ExtraData", "Quantity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MerchantShipmentLineResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of order_line
        if self.order_line:
            _dict['OrderLine'] = self.order_line.to_dict()
        # set to None if merchant_bundle_product_no (nullable) is None
        # and model_fields_set contains the field
        if self.merchant_bundle_product_no is None and "merchant_bundle_product_no" in self.model_fields_set:
            _dict['MerchantBundleProductNo'] = None

        # set to None if channel_product_no (nullable) is None
        # and model_fields_set contains the field
        if self.channel_product_no is None and "channel_product_no" in self.model_fields_set:
            _dict['ChannelProductNo'] = None

        # set to None if extra_data (nullable) is None
        # and model_fields_set contains the field
        if self.extra_data is None and "extra_data" in self.model_fields_set:
            _dict['ExtraData'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MerchantShipmentLineResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "MerchantProductNo": obj.get("MerchantProductNo"),
            "MerchantBundleProductNo": obj.get("MerchantBundleProductNo"),
            "ChannelProductNo": obj.get("ChannelProductNo"),
            "OrderLine": MerchantOrderLineResponse.from_dict(obj["OrderLine"]) if obj.get("OrderLine") is not None else None,
            "ShipmentStatus": obj.get("ShipmentStatus"),
            "ExtraData": obj.get("ExtraData"),
            "Quantity": obj.get("Quantity")
        })
        return _obj


