# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OrderSupport(str, Enum):
    """
    OrderSupport
    """

    """
    allowed enum values
    """
    NONE = 'NONE'
    ORDERS = 'ORDERS'
    SPLIT_ORDERS = 'SPLIT_ORDERS'
    SPLIT_ORDER_LINES = 'SPLIT_ORDER_LINES'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrderSupport from a JSON string"""
        return cls(json.loads(json_str))


