# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.merchant_product_request import MerchantProductRequest
from typing import Optional, Set
from typing_extensions import Self

class PatchMerchantProductDto(BaseModel):
    """
    PatchMerchantProductDto
    """ # noqa: E501
    properties_to_update: Optional[List[StrictStr]] = Field(default=None, description="Fields to update", alias="PropertiesToUpdate")
    merchant_product_request_models: Optional[List[MerchantProductRequest]] = Field(default=None, description="Products to be updated", alias="MerchantProductRequestModels")
    __properties: ClassVar[List[str]] = ["PropertiesToUpdate", "MerchantProductRequestModels"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchMerchantProductDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in merchant_product_request_models (list)
        _items = []
        if self.merchant_product_request_models:
            for _item in self.merchant_product_request_models:
                if _item:
                    _items.append(_item.to_dict())
            _dict['MerchantProductRequestModels'] = _items
        # set to None if properties_to_update (nullable) is None
        # and model_fields_set contains the field
        if self.properties_to_update is None and "properties_to_update" in self.model_fields_set:
            _dict['PropertiesToUpdate'] = None

        # set to None if merchant_product_request_models (nullable) is None
        # and model_fields_set contains the field
        if self.merchant_product_request_models is None and "merchant_product_request_models" in self.model_fields_set:
            _dict['MerchantProductRequestModels'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchMerchantProductDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "PropertiesToUpdate": obj.get("PropertiesToUpdate"),
            "MerchantProductRequestModels": [MerchantProductRequest.from_dict(_item) for _item in obj["MerchantProductRequestModels"]] if obj.get("MerchantProductRequestModels") is not None else None
        })
        return _obj


