# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from openapi_client.models.modules_tax_type import ModulesTaxType
from typing import Optional, Set
from typing_extensions import Self

class PurchaseOrderInvoiceTaxDetails(BaseModel):
    """
    PurchaseOrderInvoiceTaxDetails
    """ # noqa: E501
    tax_type: Optional[ModulesTaxType] = Field(default=None, alias="TaxType")
    tax_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="TaxRate")
    tax_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="TaxAmount")
    tax_amount_currency_code: Optional[StrictStr] = Field(default=None, alias="TaxAmountCurrencyCode")
    taxable_amount: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="TaxableAmount")
    taxable_amount_currency_code: Optional[StrictStr] = Field(default=None, alias="TaxableAmountCurrencyCode")
    __properties: ClassVar[List[str]] = ["TaxType", "TaxRate", "TaxAmount", "TaxAmountCurrencyCode", "TaxableAmount", "TaxableAmountCurrencyCode"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PurchaseOrderInvoiceTaxDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if tax_rate (nullable) is None
        # and model_fields_set contains the field
        if self.tax_rate is None and "tax_rate" in self.model_fields_set:
            _dict['TaxRate'] = None

        # set to None if tax_amount (nullable) is None
        # and model_fields_set contains the field
        if self.tax_amount is None and "tax_amount" in self.model_fields_set:
            _dict['TaxAmount'] = None

        # set to None if tax_amount_currency_code (nullable) is None
        # and model_fields_set contains the field
        if self.tax_amount_currency_code is None and "tax_amount_currency_code" in self.model_fields_set:
            _dict['TaxAmountCurrencyCode'] = None

        # set to None if taxable_amount (nullable) is None
        # and model_fields_set contains the field
        if self.taxable_amount is None and "taxable_amount" in self.model_fields_set:
            _dict['TaxableAmount'] = None

        # set to None if taxable_amount_currency_code (nullable) is None
        # and model_fields_set contains the field
        if self.taxable_amount_currency_code is None and "taxable_amount_currency_code" in self.model_fields_set:
            _dict['TaxableAmountCurrencyCode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PurchaseOrderInvoiceTaxDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "TaxType": obj.get("TaxType"),
            "TaxRate": obj.get("TaxRate"),
            "TaxAmount": obj.get("TaxAmount"),
            "TaxAmountCurrencyCode": obj.get("TaxAmountCurrencyCode"),
            "TaxableAmount": obj.get("TaxableAmount"),
            "TaxableAmountCurrencyCode": obj.get("TaxableAmountCurrencyCode")
        })
        return _obj


