# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PurchaseOrderRelatedItemExportStatus(str, Enum):
    """
    PurchaseOrderRelatedItemExportStatus
    """

    """
    allowed enum values
    """
    NONE = 'NONE'
    IN_PROGRESS = 'IN_PROGRESS'
    SUCCESS = 'SUCCESS'
    FAILURE = 'FAILURE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PurchaseOrderRelatedItemExportStatus from a JSON string"""
        return cls(json.loads(json_str))


