# coding: utf-8

"""
    ChannelEngine Merchant API

    ChannelEngine API for merchants

    The version of the OpenAPI document: 2.14.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class WebhookEventType(str, Enum):
    """
    WebhookEventType
    """

    """
    allowed enum values
    """
    ORDERS_CREATE = 'ORDERS_CREATE'
    PRODUCTS_CHANGE = 'PRODUCTS_CHANGE'
    RETURNS_CHANGE = 'RETURNS_CHANGE'
    SHIPMENTS_CHANGE = 'SHIPMENTS_CHANGE'
    NOTIFICATIONS_CREATE = 'NOTIFICATIONS_CREATE'
    BUNDLE_PRODUCTS_CHANGE = 'BUNDLE_PRODUCTS_CHANGE'
    ORDERS_CHANGE = 'ORDERS_CHANGE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of WebhookEventType from a JSON string"""
        return cls(json.loads(json_str))


